function getRandomGreeting() {
  var greetings = [
    "Imagine Looking like the mom from inside out",
    "Did you pray today",
    "Casoh, Far From veggies",
    "Imagine lookin like papa smurf",
    "I sent a virus to your computer",
    "Give you're kom her phone back",
    "Since 2020!",
    "Sub to Aztroyz!",
    "doot doot",
    "Cold as ice!",
    "Made in the US!",
    "Made by Miztyx",
    "Your search history is wild",
    "Downloading your passwords...",
    "Running Miztyz.exe",
    "WARNING: You may lose braincells if you proceed!",
    "Do you bite your ice cream?",
    "#Relatable",
    "Fortnite is cringe",
    "You got games on your phone?",
    "Powered by hamsters!",
    "*insert cool explosion*",
    "Got to go fast!",
    "My iPad passcode is 563543 btw",
    "Sponsered by RAID SHADOW LEGENDS!",
    "Sponsored by Honey!",
    "Sponsored by Miztyz",
    "Skibidi toilet #1 best show",
    "Mrbeast help me put 100 wells in africa",
    "Powered by 128 Gigs of RAM!",
    "Powered by 16MB of RAM!",
    "Do do put the milk before the cereal or after?",
    "You're a real jerk!",
    "Your not slick.. I saw what you looked up",
    "3kh0.net is here!",
    "what the dog doin?",
    "I'm gonna pop some tags",
    "Shoutout to 4chan!",
    "thx stackoverflow!",
    "are you a gaemer?",
    "It is time to get funky!",
    "We didn't start the fire! It was always burning, since the world's been turning!",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "Living in Spain without the S",
    "Shoutout to Piplup!",
    "Shoutout to 3kh0!",
    "Woo! /g/",
    "your moms so fat she has her own gravitational pull",
    "Powered by your mom",
    "Why is there furry images on you'r chromebook.",
    "Dont turn emo!!!",
    "One dono saves a homo.",
    "Why is your groupchat named dont give africa water!!",
    "Why do they call it oven if you oven the cold food of out hot eat the food",
    "No fun allowed",
    "Your toes will be pulled tonight",
    "i do love buying birth certificates from the black market! - Piplup",
    "'If you are trash go play Fortnite you loser' - Sun Tzu, Art of war",
    "Echo is not a furry I swear",
    "i wanted free vbucks :(",
    "Avocados \ud83e\udd51 from Mexico \ud83c\uddf2\ud83c\uddfd",
    "reload for another message",
    "Why does the discord server exist",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "Techonoblade never dies!",
    "And just to think I knew him before he was famous",
    "Trust me, I did not copy Minecraft with this",
    "It is everyday bro",
    "That proves you are unusual",
    "What's my age again?",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "Roblox? Cringe!",
    "I love skibidi toilet",
    "Free pallenstine",
    "NUKE INCOMING!",
    "I spent too much time making these",
  ];
  var randomIndex = Math.floor(Math.random() * greetings.length);
  return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
